### PR TITLE
Stage 2: Markup and JSX

### PR DESCRIPTION
**Pull request by MJourno**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Thanks for your work, the project looks quite good! However, some refactoring will be necessary, please find description of issues below. I hope they'll be easy to fix

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* The content of the page should have limited width. Currenlty, on large screen resolutions, it's stretched to the whole width (e.g. on 2800px the content will occupy the whole screen width).
* On "Home" page, there should be saved cards: https://prnt.sc/1aSncLyHpRVW, only search result cards.
* In popups, Times New Roman is rendered for inputs and labels.
* https://prnt.sc/AR1K1q8al6A4 Content dhouesn't get outside the card boundaries.
* There should be three cards in a row for tablets and desktops https://prnt.sc/9v1xb2_cRzWD
* https://prnt.sc/m_LcQOrLecsC Logout icon is incorrectly aligned

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* "Home" page scrolls on 401 - 507
* Gaps between cards are too big: https://prnt.sc/BZjlbmoZK_Ey All tablet and desktop screens need three cards in a row

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Link to Saved-news doesn't work, saved-news route leads to home.

- [ ]  Classes are named according to BEM specifications.

* `searchResults____container` typo in the class name, three underscores
* `newsCardList__cards-grid` Elements can't be used outside of their block
* `popup__input_type_error` modifiers can't be used without modified elements.

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* newsCard - li can't be direct children of div, the cards should be in a list.
* `about__text` Plese don't use br as a divider between paragraphs. There should be several paragraphs, not a single paragraph with br inside

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

* Main background image shouldn't be in svg, please use raster graphics format for pictures like this (jpg or png).

## Number of points: 48

**Comment by ImaliaNsk** [comment]
Good job on corrections! Some more refactoring will be necessary, but the project has been improved.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* There should be no "saved" cards on the home page: https://skr.sh/sKEWFFs9dKj, only search results. Saved articles should be on a separate page. It needs a different design, different header, for example. Please check figma. Note also that the cards shouldn't be stretched so wide as on the screenshot I attached.

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* scroll on 560 https://prnt.sc/RlkekQv5ZNmq
* https://skr.sh/sKE2WyS8Hdh scroll on 521 - 656

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Link to Saved-news doesn't work, saved-news route leads to home.

- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.

* https://skr.sh/sKEWxuUWblm Please fix all similar cases.

- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

* Main background image shouldn't be in svg, please use raster graphics format for pictures like this (jpg or png).

## Number of points: 59

**Comment by ImaliaNsk** [comment]
Good job, only a few points short! There are a few issues to correct and the project will be accepted. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* The navigation menu on saved-news doesn't match the design, please check the colors
* The navigation menu button on mobile screens isn't possible to see on saved-news, it's white on white

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* saved-news scrolls on 521 - 656
- home scrolls on 521 - 656

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.

* https://skr.sh/sKEWxuUWblm Please fix all similar cases.

- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

* Main background image shouldn't be in svg, please use raster graphics format for pictures like this (jpg or png).

## Number of points: 71

**Comment by FiLLa-FaS** [comment]
Hi! You've got more than 80 points, so your project has been accepted! Btw you still can fix all the rest issues below to make your project perfect. Good luck on the next stage!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Times New Roman font is rendered on the page for all text elements instead of needed fonts according to the mockup
    * `navigation__signin` in mobile nav menu shouldn't extend outside the nav menu
    * `navigation__logo` should be visible for nav menu on `saved-news` page (now it's black on black)
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * You should add at least one alternative font and generic font-family for all `font-family` styles on the page.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 86

**Pull request merged**
